apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: survey-hpa
  namespace: spring-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: survey-web
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
