apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: survey-app
  namespace: spring-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: survey-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
status:
  observedGeneration: 1
  lastScaleTime: <some-time>
  currentReplicas: 2
  desiredReplicas: 2
  conditions: 
    - AbleToScale
      ScalingActive
      ScalingLimitted
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      currentAverageUtilization: 0
      currentAverageValue: 0
