apiVersion: v1
kind: Service
metadata:
  name: survey-postgres
  labels:
    app: survey-app
  namespace: spring-app
spec:
  ports:
  - port: 5432
  selector:
    app: survey-app
    tier: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: survey-postgres
  labels:
    app: survey-app
  namespace: spring-app
spec:
  selector:
    matchLabels:
      app: survey-app
      tier: postgres
  template:
    metadata:
      labels:
        app: survey-app
        tier: postgres
    spec:
      containers:
      - image: postgres:9.6
        name: postgres
        env:
        - name: POSTGRES_USER
          value: duc2495
        - name: POSTGRES_PASSWORD
          value: duc2495
        - name: POSTGRES_DB
          value: hrs-training
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          readOnly: false
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: nfs-postgres-pvc
