apiVersion: v1
kind: Service
metadata:
  name: survey
  labels:
    app: survey-app
  namespace: spring-app
spec:
  ports:
    - port: 8080
      nodePort: 30303
  selector:
    app: survey-app
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: survey
  labels:
    app: survey-app
  namespace: spring-app
spec:
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
        tier: frontend
    spec:
      containers:
      - name: survey
        image: duc2495/surveyapp:v1.4
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
        readinessProbe:
          httpGet:
            host: 
            path: /SpringMVC/
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 5
