apiVersion: v1
kind: Service
metadata:
  name: survey-app
  labels:
    app: survey-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: survey-app
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: survey-app
  labels:
    app: survey-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
        tier: frontend
    spec:
      containers:
      - name: survey-app
        image: duc2495/surveyapp:v1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
        readinessProbe:
          httpGet:
            host: 
            path: /SpringMVC/
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 5
        livenessProbe:
          httpGet:
            host: 
            path: /SpringMVC/
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
