apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-influxdb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.10.1
    path: "/var/nfs/k8s-storage/influxdb"
